import React from 'react'
import { Helmet } from 'react-helmet'
function PrivacyPolicy() {
  return (

<div class="bg-white pt-20 h-[100vh]" >
        <Helmet><title>Pro Work - Privacy Policy</title></Helmet>
        <div class=" h-full w-screen bg-[#33806b] 1xs:mx-auto px-2 1xs:px-6 py-4 overflow-y-scroll shadow-shadow5px " id='TermsAndPrivacyScroll'>
            <div class='w-full flex'>
              <h1 class="text-3xl font-bold mb-4 text-[#f2da1d]">Privacy Policy for Pro Work </h1>
            </div>
            <p class="mb-4 text-[#f2da1d]">Last updated on June 20, 2025</p>
            <div class="mb-4 text-base text-white">
                <ul className="list-disc pl-5 marker:text-[#f2da1d]">
                <li className='py-2 px-4'>This Privacy Policy is effective as of the date set forth above and applies to all users of the Platform.</li> 
                <li className='py-2 px-4'>This Policy applies to Prowork Ventures Private Limited (hereinafter referred to as “Pro Work” or “the Company”), a company incorporated under the Companies Act, 2013 and having its registered office at Mama bhanja ka talab, Prayagraj, Naini (Allahabad), Allahabad, Allahabad- 211008, Uttar Pradesh, and its subsidiaries, holding company, and affiliates. The Company is the owner of the website www.prowork.org.in and the mobile application ‘Pro Work’ (collectively, the “Platform”).</li>
                <li className='py-2 px-4'>This privacy policy (“Privacy Policy”) describes the policies and procedures applicable to the collection, use, storage, disclosure, and protection of your information shared with us while you use the Platform. For the purpose of this Privacy Notice, "We", "Us", or "Our" refers to Prowork Ventures Private Limited and its affiliates, as the context may require; and the terms “You”, “Your”, “Yourself”, or “User” refer to users of the Platform.</li>
                <li className='py-2 px-4'>We value the trust you place in us. That is why we maintain reasonable security standards to protect your information and transactions.</li>
                <li className='py-2 px-4'>Please read this Privacy Policy carefully before using or registering on the Platform, or accessing any material, information, or services available through the Platform.</li>
                <li className='py-2 px-4'>This Privacy Policy outlines how your information is collected, stored, processed, disclosed, transferred, or otherwise handled by us. It does not apply to any information that is collected by third-party services or websites you may access through the Platform.</li>
                <li className='py-2 px-4'>By visiting the Platform or creating an account on the Platform, you accept and agree to the terms of this Privacy Policy and consent to our collection, use, storage, and sharing of your personal information (as defined below) in accordance with this Policy.</li>
                <li className='py-2 px-4'>If you are under the age of 18 years, you (i) confirm that you are using the Platform under the supervision and with the permission of a parent or legal guardian who is eligible to enter into a contract under the Indian Contract Act, 1872, and (ii) agree that such parent or legal guardian has accepted this Privacy Policy on your behalf and thereby bound you to the terms herein.</li>
                <li className='py-2 px-4'>We may update this Privacy Policy to comply with business, legal, or regulatory changes. If we make any material changes, we will notify you through appropriate means such as an announcement on the Platform or direct communication. Your continued use of the Platform after any such update shall constitute your acceptance of the revised Privacy Policy.</li>
                <li className='py-2 px-4'>This Privacy Policy is to be read together with our Terms of Service and is incorporated therein by reference. All capitalized terms used but not defined herein shall have the same meaning as assigned in the Terms of Service.</li>
                </ul>
            </div>
            <div class='pb-5 px-4 text-white'>
                <h2 class='font-bold text-[#f2da1d]'>1. Collection of Information: &nbsp; <span className='text-white'>We collect various information from You when You access or visit the Platform, register or set up an Account on the Platform or use the Platform. You may browse certain sections of the Platform and the Content, without registering an Account on the Platform. However, to avail certain services on the Platform, You are required to set up an Account on the Platform. This Privacy Notice applies to information(s), as mentioned below and collected about You:</span></h2>
                <p className='text-base py-2 px-4'>1.1 &nbsp; <span className='underline text-[#f2da1d]'>Personal Information:</span> &nbsp; You may voluntarily provide certain information to Us while registering on the ProWork Platform or availing Our services. This information may include, but is not limited to, your full name, mobile number, email address, date of birth, gender, age, residential address, and identity verification documents such as PAN card, passport, driving license, voter ID, or any other government-recognized proof of identity. Additionally, We may collect income-related details, professional or business information, lifestyle or health-related inputs (if applicable), photographs, videos, or other verification documents as may be required by regulatory authorities. We may also collect technical data such as your IP address, web requests, device type, browser type, operating system, connection details, and related browsing metadata. This collectively constitutes your “Personal Information.” Providing such information is voluntary, and by doing so, you acknowledge and agree that ProWork may collect, use, store, process, share, or transfer such data in accordance with applicable laws and this Privacy Policy.</p>
                <p className='text-base py-1 px-4'>1.2 &nbsp; <span className='underline text-[#f2da1d]'>Transactional Information:</span> &nbsp;  If You choose to avail the services through the Platform, We will also collect and store information about Your transactions including transaction status, order history, number of transactions, details and Your behaviour or preferences on the Platform. All transactional information gathered by Us shall be stored on servers, log files and any other storage system owned by any of Us or by third parties. Your Short Messaging Service (SMS(es)) that are stored on Your device for the purposes of, including but not limited to, registering You and Your device for the purpose of Products and services, OTPs for logins, enhancing Your security are also collected and processed by Us.</p>
                <p className='text-base py-1 px-4'>1.3 &nbsp; <span className='underline text-[#f2da1d]'>Location based information:</span> &nbsp; 
                    <p className='py-2 px-4'>When you access or use the ProWork Platform (via mobile, tablet, or other devices), we may collect details like your location, IP address, internet bandwidth, device model, and browser type. If you allow location access, we may gather real-time location data while the app runs in the foreground or background. You can disable this access anytime, although it may limit certain functionalities.</p>
                    <p className='py-2 px-4'>This information helps us deliver a safe, smooth, personalized experience and tailor our services to your preferences. In addition to Personal Information, we may also collect non-personal data such as URLs, device attributes, previous sites visited, or third-party app usage. We use cookies and similar tools for authentication, saving preferences, analytics, and to enhance security and advertising relevance.</p>
                    <p className='py-2 px-4'>While browsing ProWork, you're not required to reveal Personal Information unless using specific features. Certain fields may be mandatory to use particular services. We may track usage behavior to better understand and serve you, ensuring customer support, resolving disputes, or enhancing the platform.</p>
                    <p className='py-2 px-4'>Correspondence you send us (e.g., emails or feedback) may also be stored for service improvement. ProWork retains personal and usage information as long as necessary, strictly in accordance with this Privacy Policy.</p>
                </p>
                <p className='text-base py-1 px-4'>1.4 &nbsp; <span className='underline text-[#f2da1d]'>Additional Information:</span> &nbsp; We may obtain information You voluntarily share with Us through interactions on Our social media channels, participation in surveys or by submission of feedback. Through these engagements and in order to provide the services You have accessed on Our Platform, We may also gain insights into certain Personal Information, such as Your preferences for Products and services.</p>
            </div>
            <div class='pb-5 px-4 text-white'>
                <h2 class='font-bold text-[#f2da1d]'>2. Use of information: <span className='text-white'> &nbsp; We use the information in accordance with law, for the following:</span></h2>            
                <p className='py-1 px-4'> <span className='text-[#f2da1d]'>.</span> &nbsp; to create Your account and verification of Your identity and access privileges</p>
                <p className='py-1 px-4'> <span className='text-[#f2da1d]'>.</span> &nbsp; to provide You access to the services offered by ProWork, including those facilitated through our Service Professionals or business partners, and to enhance and improve the quality of services You request via the Platform;</p>
                <p className='py-1 px-4'> <span className='text-[#f2da1d]'>.</span> &nbsp; for internal business purposes and services, including without limitation, warehousing services, delivery services, IT support services, and data analysis services;</p>
                <p className='py-1 px-4'> <span className='text-[#f2da1d]'>.</span> &nbsp; to resolve disputes, to manage Your requests and complaints, administer Our service and diagnose/ troubleshoot technical problems;</p>
                <p className='py-1 px-4'> <span className='text-[#f2da1d]'>.</span> &nbsp; to design and improve the products and services and customer relationship management processes;</p>
                <p className='py-1 px-4'> <span className='text-[#f2da1d]'>.</span> &nbsp; to collect money from You in relation to the services,</p>
                <p className='py-1 px-4'> <span className='text-[#f2da1d]'>.</span> &nbsp; to inform You about online and offline offers, products, services, and updates;</p>
                <p className='py-1 px-4'> <span className='text-[#f2da1d]'>.</span> &nbsp; to customize Your experience on the Platform or share marketing material with You;</p>
                <p className='py-1 px-4'> <span className='text-[#f2da1d]'>.</span> &nbsp; to detect, prevent and protect Us from any errors, fraud and other criminal or prohibited activity on the Platform;</p>
                <p className='py-1 px-4'> <span className='text-[#f2da1d]'>.</span> &nbsp; to enforce and inform about Our Terms of Use;</p>
                <p className='py-1 px-4'> <span className='text-[#f2da1d]'>.</span> &nbsp; to process and fulfil Your request for services or respond to Your comments, and queries on the Platform;</p>
                <p className='py-1 px-4'> <span className='text-[#f2da1d]'>.</span> &nbsp; to audit, monitor and enhance Our internal processes for smooth functioning of Our Platform and also to ensure effectiveness of internal procedures.</p>
                <p className='py-1 px-4'> <span className='text-[#f2da1d]'>.</span> &nbsp; to contact You through email, SMS, WhatsApp, telephone and any other mode of communication in relation to the services;</p>
                <p className='py-1 px-4'> <span className='text-[#f2da1d]'>.</span> &nbsp; to allow Our service providers, business partners and/or associates to communicate with You;</p>
                <p className='py-1 px-4'> <span className='text-[#f2da1d]'>.</span> &nbsp;  to carry out marketing, advertising or promotional activities</p>
            </div>
            <div className='pb-5 px-4 text-white'>
                <h2 class='font-bold text-[#f2da1d]'>3. Sharing of Information</h2>
                <p className='py-2 px-4'>3.1 &nbsp; <span className='underline text-[#f2da1d]'>General Information Disclosures:</span> &nbsp; 
                    <li className='py-1 px-4'>To our subsidiaries and affiliates, which are entities under common ownership or control of our ultimate company Prowork Ventures Private Limited.</li>
                    <li className='py-1 px-4'>To contractors, advertisers/service providers who are bound by contractual obligations to keep personal information confidential and use it only for the purposes for which we disclose it to them.</li>
                    <li className='py-1 px-4'>To third-parties to market their products or services to you if you have consented to receive the promotional updates. We contractually require these third-parties to keep personal information confidential and use it only for the purposes for which we disclose it to them.</li>
                    <li className='py-1 px-4'>To fulfill the purpose for which you provide it.</li>
                </p>
                <p className='py-2 px-4'>3.2 &nbsp; <span className='underline text-[#f2da1d]'>Service Providers:</span> &nbsp; We may share your information with outside vendors that we use for a variety of purposes, such as to send you communications via emails, messages or tele-call to inform you about our products that may be of interest to you, push notifications to your mobile device on our behalf, provide voice recognition services to process your spoken queries and questions, help us analyze use of our Services, and process and collect payments. Some of our products, services and databases are hosted by third party hosting services providers. We also may use vendors for other projects, such as conducting surveys or organizing sweepstakes for us. We may share information about you with these vendors only to enable them to perform their services.</p>
                <p className='py-2 px-4'>3.3 &nbsp; <span className='underline text-[#f2da1d]'>Legal Purposes:</span> &nbsp; We may share your information when we believe in good faith that such sharing is reasonably necessary in order to investigate, prevent, or take action regarding possible illegal activities or to comply with legal process. We may also share your information to investigate and address threats or potential threats to the physical safety of any person, to investigate and address violations of this Privacy Policy or the Terms of Service, or to investigate and address violations of the rights of third parties and/or to protect the rights, property and safety of Zomato, our employees, users, or the public. This may involve the sharing of your information with law enforcement, government agencies, courts, and/or other organizations on account of legal request such as subpoena, court order or government demand to comply with the law.</p>
                <p className='py-2 px-4'>3.4 &nbsp; To enforce or apply our Terms of Use and other agreements, including for billing and collection purposes.</p>
                <p className='py-2 px-4'>3.5 &nbsp; If we believe disclosure is necessary or appropriate to protect the rights, property, or safety of Pro Work, our customers or others. This includes exchanging information with other companies and organizations for the purposes of fraud protection and credit risk reduction.</p>
                <p className='py-2 px-4'>3.6 &nbsp; <span className='underline text-[#f2da1d]'>Consent:</span> &nbsp; We may share your information in any other circumstances where we have your consent.</p> 
            </div>
            <div className='pb-5 px-4 text-white'>
                <h2 className='font-bold text-[#f2da1d]'>4. Security Precautions and Measures: <span className='text-white'>The Platform has reasonable security measures and safeguards in place to protect Your privacy and Personal Information from loss, misuse, unauthorized access, disclosure, destruction, and alteration, in compliance with applicable laws. Further, whenever You change or access Your Account on the Platform or any information relating to it, the use of a secure server is offered. It is further clarified that You have and so long as You access and/or use the Platform (directly or indirectly) the obligation to ensure that You shall at all times take adequate physical, managerial, and technical safeguards, at Your end, to preserve the integrity and security of Your information which shall include and not be limited to Your Personal Information.</span></h2>
                <p className='py-4'>You will be responsible for maintaining the confidentiality of the Account information and are fully responsible for all activities that occur under Your Account. You agree to (a) immediately notify Us of any unauthorised use of Your Account information or any other breach of security, and (b) ensure that You exit from Your Account at the end of each session. We cannot and will not be liable for any loss or damage arising from Your failure to comply with this provision. You may be held liable for losses incurred by any of Us or any other user of or visitor to the Platform due to authorised or unauthorised use of Your Account as a result of Your failure in keeping Your Account information secure and confidential. Additionally, You are responsible for keeping Your login ID and password confidential and secure. Please avoid sharing Your login credentials, password or OTP with anyone. It is Your responsibility to promptly inform Us of any actual or suspected compromise of Your Personal Information.</p>
                <p className='py-4'>When payment information is being transmitted on or through the Platform, it will be protected by encryption technology. Hence, We cannot guarantee that transmissions of Your payment-related information or Personal Information will always be secure or that unauthorized third parties will never be able to defeat the security measures taken by Us or Our third-party service providers. We assume no liability or responsibility for disclosure of Your information due to errors in transmission, unauthorised third-party access, or other causes beyond Our control. You play an important role in keeping Your Personal Information secure. You shall not share Your Personal Information or other security information for Your Account with anyone. We have undertaken reasonable measures to protect Your rights of privacy with respect to Your usage of the Platform and the services. However, We shall not be liable for any unauthorised or unlawful disclosures of Your Personal Information made by any third parties who are not subject to Our control.</p>
            </div>
            <div className='pb-5 px-4 text-white'>
                <h2 class='font-bold text-[#f2da1d]'>5. Retention of Your Personal Information: <span className='text-white'>We maintain records of Your Personal Information only till such time it is required for the Purposes, or for as long as required by applicable law. To the extent possible, We endeavour to store Personal Information and Sensitive Personal Information within India. When You request Us to erase Your information, We will honour the said request, but We may retain certain information about You for the purposes authorized under this Privacy Notice unless prohibited by law.  However, We may retain Your Personal Information if We believe it may be necessary to prevent fraud or future abuse, to enable Us to exercise legal rights and/or defend against legal claims.</span></h2>                
            </div>
            <div className='pb-5 px-4 text-white'>
                <h2 class='font-bold text-[#f2da1d]'>6. Right to erasure and Right to Withdraw Your consent: <span className='text-white'>You may choose to withdraw Your consent provided hereunder at any point in time.</span></h2>
                <p className='py-4'>In case You do not provide Your consent or later withdraw Your consent, We request You not to access the Platform, Content or use the services. We shall also cease to provide You any services and/or Content on the Platform and/or features of the Platform once You withdraw Your consent. In such a scenario, We will remove Your information (personal or otherwise) or de-identify it so that it is anonymous and not attributable to You. In the event, We retain the Personal Information post withdrawal or cancellation of Your consent, it shall retain it only for the period permitted under applicable laws. You shall have the right to request that We remove Your Personal Information from Our systems.</p>
            </div>
            <div className='pb-5 px-4 text-white'>
                <h2 class='font-bold text-[#f2da1d]'>7. Question ?</h2>
                <p className='py-4'>Please feel free to contact at this <span className='text-[#f0da31]'>prowork.professional24x7@gmail.com</span> regarding any questions on the Privacy Notice. We will use reasonable efforts to respond promptly to requests, questions or concerns You may have regarding Our use of Your Personal Information. Except where required by law, We cannot ensure a response to questions or comments regarding topics unrelated to this Privacy Notice or the privacy practices specified herein.</p>
            </div>
        </div>
    </div>
  )
}

export default PrivacyPolicy