import React from 'react'
import { Helmet } from 'react-helmet'
function Terms() {
  return (
    
    <div class="bg-white pt-20 h-[100vh]" >
        <Helmet>
            <title>Pro Work - Terms of Service</title>
            <meta
                name="description"
                content="Read the terms and conditions for using ProWork services. Transparency and trust for all users and workers on our platform."
            />
            <link rel="canonical" href="https://prowork.org.in/terms-of-service" />
        </Helmet>
        <div class="h-full w-screen bg-[#33806b] 1xs:mx-auto px-2 1xs:px-6 py-4 overflow-y-scroll shadow-shadow5px" id='TermsAndPrivacyScroll'>
            <div class='w-full flex'>
              <h1 class="text-3xl font-bold mb-4 text-[#f2da1d]">Terms of Service for Pro Work </h1>
            </div>

            <p class="mb-4 text-[#f2da1d]">Last updated on June 20, 2025</p>
            <p class="mb-4 text-base text-white">Welcome to ProWork. Please read these Terms of Service ("Terms") carefully before using the website <a href="https://prowork.org.in" className='text-[#f0db40]'>www.prowork.org.in</a> or the Pro Work mobile application (collectively, the "Platform"). By accessing or using our Platform and Services, you agree to be bound by these Terms. If you do not agree to these Terms, please do not use our Services.</p>
         
            <div class='pb-5 px-4 text-white'>
                <h2 class='font-bold text-[#f2da1d]'>1. General</h2>
                <p className='text-base py-1 px-4'>1.1 &nbsp; Definition of “ProWork” - For the purposes of these Terms, the term “ProWork” refers collectively to the services and functionalities provided through the official ProWork website (www.prowork.org.in) and the ProWork mobile applications, including both Android and iOS versions. Together, these platforms constitute the “Platform” as referred to throughout these Terms.</p>
                <p className='text-base py-1 px-4'>1.2 &nbsp; These Terms govern your use of the services provided by ProWork Ventures Pvt. Ltd. through the Platform. By using the Platform, you represent that you have the legal authority to accept these Terms on your behalf or on behalf of any entity you represent.</p>
                <p className='text-base py-1 px-4'>1.3 &nbsp; By using the Services, you represent and warrant that you have full legal capacity and authority to agree to and bind yourself to these Terms. If you represent any other person, you confirm and represent that you have the necessary power and authority to bind such person to these Terms.</p>
                <p className='text-base py-1 px-4'>1.4 &nbsp; By using the Services, you agree that you have read, understood, and are bound by, these Terms, as amended from time to time, and that you will comply with the requirements listed here. These Terms expressly supersede any prior written agreements with you. If you do not agree to these Terms, or comply with the requirements listed here, please do not use the Services.</p>
            </div>
            <div class='pb-5 px-4 text-white'>
                <h2 class='font-bold text-[#f2da1d]'>2. Services</h2>
                <p className='text-base p-4'>2.1 &nbsp; Prowork Ventures Pvt. Ltd. (“Prowork”, “we”, “us”, or “our”) provides a platform that connects customers (“Customers” or “you”) with independent third-party service providers (“Service Professionals”) to facilitate the provision of home-based services, including but not limited to cleaning, plumbing, electrical work, and other related services (collectively, the “Services”).</p>
                <p className='text-base p-4'>2.2 &nbsp; The Services include the provision of the Platform that enables you to arrange and schedule different home-based services with independent third-party service providers of those services (“Service Professionals”). As a part of the Services, Prowork facilitates the transfer of payments to Service Professionals for the services they render to you and collects payments on behalf of such Service Professionals.</p>
                <p className='text-base p-4'>2.3 &nbsp; Service Professionals are solely liable and responsible for the Services that they offer or otherwise provide through the Platform. Prowork and its affiliates do not employ Service Professionals, nor are Service Professionals agents, contractors, or partners of Prowork or its affiliates. Service Professionals do not have the ability to bind or represent Prowork.</p>
                <p className='text-base p-4'>2.4 &nbsp; The Platform is for your personal and non-commercial use only. Please note that the Platform is intended for use only within India.</p>
                <p className='text-base p-4'>2.5 &nbsp; A key part of the Services is Prowork’s ability to send you text messages, electronic mails, or WhatsApp messages, including in connection with your bookings, your utilisation of the Services, or as a part of its promotional and marketing strategies. While you may opt out of receiving these text messages by contacting through the in-Platform settings , you agree and acknowledge that this may impact Prowork’s ability to provide the Services (or a part of the Services) to you.</p>
                <p className='text-base p-4'>2.6 &nbsp; In certain instances, you may be required to furnish identification proof to avail the Services and also to provide the services, and hereby agree to do so. A failure to comply with this request may result in your inability to use the Services and even provide the services(for service professionals).</p>
            </div>
            <div className='pb-5 px-4 text-white'>
                <h2 class='font-bold text-[#f2da1d]'>3. Account Creation</h2>
                <p className='text-base p-4'>3.1 &nbsp; To avail the Services, you will be required to create an account on the Platform (“Account”). For this Account, you may be required to furnish certain details, including but not limited to your phone number. To create an Account, you must be at least 18 years of age.</p>
                <p className='text-base p-4'>3.2 &nbsp; You warrant that all information furnished in connection with your Account is and shall remain accurate and true. You agree to promptly update your details on the Platform in the event of any change to or modification of this information.</p>
                <p className='text-base p-4'>3.3 &nbsp; You are solely responsible for maintaining the security and confidentiality of your Account and agree to immediately notify us of any disclosure or unauthorised use of your Account or any other breach of security with respect to your Account.</p>
                <p className='text-base p-4'>3.4 &nbsp; You are liable and accountable for all activities that take place through your Account, including activities performed by persons other than you. We shall not be liable for any unauthorised access to your Account.</p>
                <p className='text-base p-4'>3.5 &nbsp; In order to register as a Service Professional on the Platform and to maintain the integrity and security of the Services, you agree to provide valid government-issued identification for verification purposes, including but not limited to a copy of your Aadhaar card. Such information shall be used solely for identity verification, background checks, and other legitimate purposes in accordance with our Privacy Policy. Failure to provide accurate and verifiable information may result in suspension or termination of your access to the Platform.</p>
                <p className='text-base p-4'>3.6 &nbsp; You agree to receive communications from us regarding (i) requests for payments, (ii) information about us and the Services, (iii) promotional offers and services from us and our third party partners, and (iv) any other matter in relation to the Services.</p>
            </div>
            <div className='pb-5 px-4 text-white'>
            <h2 class='font-bold text-[#f2da1d]'>4. User Content</h2>
                <p className='text-base p-4'>4.1 &nbsp; Our Platform may contain interactive features or services that allow users who have created an account with us to post, upload, publish, display, transmit, or submit comments, reviews, suggestions, feedback, ideas, or other content on or through the Platform (“User Content”).</p>
                <p className='text-base p-4'>4.2 &nbsp; As part of the effective provision of the Services and quality control purposes, we may request reviews from you about Service Professionals and you agree and acknowledge that Service Professionals may provide reviews about you to us. You must not knowingly provide false, inaccurate, or misleading information in respect of the reviews. Reviews will be used by us for quality control purposes and to determine whether Customers and Service Professionals are appropriate users of the Platform. If we determine at our sole discretion that you are not an appropriate user, we reserve the right to cancel your registration and remove you from our Platform.</p>
                <p className='text-base p-4'>4.3 &nbsp; You grant us a non-exclusive, worldwide, perpetual, irrevocable, transferable, sublicensable, and royalty-free licence to use User Content for the limited purposes of advertising and promoting the Services, or furnishing evidence before a court or authority of competent jurisdiction under applicable laws.</p>
                <p className='text-base p-4'>4.4 &nbsp; You agree and acknowledge that Prowork may, without notice to you, remove, or otherwise restrict access to User Content that, in its sole discretion, violates these Terms.</p>
            </div>
            <div className='pb-5 px-4 text-white'>
            <h2 class='font-bold text-[#f2da1d]'>5. Consent</h2>
                <p className='text-base p-4'>5.1 &nbsp; You agree that we may, in accordance with our Privacy Policy, collect and use your personal data. The Privacy Policy is available at https://www.prowork.org.in/privacy-policy and it explains the categories of personal data that we collect or otherwise process about you and the manner in which we process such data.</p>
                <p className='text-base p-4'>5.2 &nbsp; In addition to any consent you may provide pursuant to the Privacy Policy, you hereby consent to us sharing your information with our affiliates or other third party service providers .We may use information and data pertaining to your use of the Services for provision of the Services, analytics, trend identification, and purposes of statistics to further enhance the effectiveness and efficiency of our Services, and provision of beneficial schemes, new offers, and for experience enhancement.</p>
                <p className='text-base p-4'>5.3 &nbsp; Subject to applicable laws, we may be directed by law enforcement agencies or the government and related bodies to disclose data in relation to you in connection with criminal or civil proceedings. You understand and agree that in such instances we shall have the right to share such data with relevant agencies or bodies.</p>
            </div>
            <div className='pb-5 px-4 text-white'>
            <h2 class='font-bold text-[#f2da1d]'>6. Orders</h2>
                <p className='p-4'>6.1 &nbsp; <span className='underline text-[#f2da1d]'>Orders:</span> The Platform permits you to request various Services at a time when you book the service. To make a booking, you should follow the instructions on the Platform and provide necessary information. We use reasonable efforts to enable you to find a Service Professional who is able to provide that service at the requested time. If, in the unlikely event the Service Professional deny the service, we will contact you to find an alternative Service Professional.</p>
                <p className='p-4'>6.2 &nbsp; <span className='underline text-[#f2da1d]'>Confirmation:</span> Once you place a request we will provide confirmation of the booking via SMS, email or a push notification. Once your booking has been confirmed, you will be required to make the payment in accordance with these Terms or as indicated on the Platform. Once a Service Professional has been identified for the requested Services, you shall receive confirmation in App or Website or via SMS, email or a push notification.</p>
                <p className='p-4'>6.3 &nbsp; <span className='underline text-[#f2da1d]'>Cancellations:</span> Bookings that are cancelled before confirmation on the Platform will not be charged. Prowork’s cancellation policy sets out applicable cancellation fees.</p>
                <p className='p-4'>6.4 &nbsp; <span className='underline text-[#f2da1d]'>Substitution:</span> In case of the unavailability of, or cancellation by a selected Service Professional, we will offer you a substitute of the Service Professional from among our registered Service Professionals.</p>
            </div>
            <div className='pb-5 px-4 text-white'>
                <h2 class='font-bold text-[#f2da1d]'>7. Pricing and Payment terms</h2>
                <p className='p-4'>7.1 &nbsp; Pro Work reserves the right to charge you for the different Services you may avail and/or for any other facilities you may opt for, from time to time, on or via the Platform.</p>
                <p className='p-4'>
                    7.2 &nbsp; <span className='underline text-[#f2da1d]'>Charges and fees in terms of services: </span>
                    <span className='block px-10 py-2'>(a) &nbsp;&nbsp;&nbsp;&nbsp;In respect of Services that you seek to avail through the Platform, you shall be required to pay Service Professionals the amount indicated at the time of booking as well as amounts towards (a) any additional Services you may avail, (b) out of pocket expenses incurred by the Service Professional, and (c) expenses arising out of the purchase of goods required or utilised for the performance of the Service (“Charges”). In addition to the Charges payable to Service Professionals, Prowork reserves the right to charge you a convenience fee for facilitating the booking and transferring payments to the Service Professional (this fee is referred to as “Fees”). You acknowledge that the final bill you receive may include additional charges, including without limitation, a safety fee, warranty fee, insurance fee, or Service Professional welfare fee.</span>
                    <span className='block px-10 py-2'>(b) &nbsp;&nbsp;&nbsp;&nbsp;Prowork shall notify you of the applicable Charges, Fees, and payment methods at the time of booking. Generally, you may make payments for Services through credit cards, debit cards, net banking, wallets, UPI or cash upon completion of the Service. We have the right to modify and otherwise restrict the modes of payment available to you. You acknowledge that certain payment methods such as cash upon completion may not always be available to you as a payment method. For the avoidance of doubt, in the event you pay through the method of ‘cash upon completion’, you acknowledge that you will be required to pay both Charges and Fees to the Service Professional.</span>
                    <span className='block px-10 py-2'>(c) &nbsp;&nbsp;&nbsp;&nbsp;The Charges and Fees may be payable at the time of making a booking, or upon the completion of the Service, as specified by Prowork.</span>
                    <span className='block px-10 py-2'>(d) &nbsp;&nbsp;&nbsp;&nbsp;For the avoidance of doubt, please note that the Charges are payable to Service Professionals, and Pro Work acts as a limited collection agent on behalf of such Service Professionals to collect and transfer amounts due to them.</span>
                    <span className='block px-10 py-2'>(e) &nbsp;&nbsp;&nbsp;&nbsp;<span className='underline'>Taxes:</span> All Charges and Fees are inclusive of applicable taxes.</span>
                    <span className='block px-10 py-2'>(f) &nbsp;&nbsp;&nbsp;&nbsp;Prowork reserves the right to reasonably amend the Charges and Fees at any time at its sole discretion. A change in Fees shall not impact any bookings that have been confirmed before the publication of the revised Fees on the Platform.</span>
                    <span className='block px-10 py-2'>(g) &nbsp;&nbsp;&nbsp;&nbsp;Charges and Fees that you pay are final and non-refundable, unless otherwise determined by Prowork or required by the applicable laws. Under certain laws, you may be entitled to a refund or other remedies for a failure in the provision of the Services.</span>
                    <span className='block px-10 py-2'>(h) &nbsp;&nbsp;&nbsp;&nbsp;You acknowledge and agree that Charges and Fees applicable in certain geographical areas may increase substantially during times of high demand. Prowork will use reasonable efforts to inform you of the Charges and Fees that may apply. However, by using the Services, you will be responsible for the Charges and Fees incurred under your Account regardless of your awareness of such Charges or Fees.</span>
                </p>
                <p className='p-4'>7.3 &nbsp; <span className='underline text-[#f2da1d]'>Payment Gateway:</span>  We may use a third-party payment gateway (“Payment Processor”) to bill you through your selected mode of payment. The processing of payments will be subject to the terms and policies of such Payment Processor in addition to these Terms. We shall not be liable for any error of the Payment Processor. In the event of any unsuccessful payment, the money debited shall be credited in accordance with the terms of the Payment Processor.</p>
                <p className='p-4'>7.4 &nbsp; <span className='underline text-[#f2da1d]'>Cancellation:</span> You may elect to cancel your request for services from a Service Professional at any time prior to such Service Professional’s arrival, in which case you may be charged a cancellation fee in accordance with Prowork’s cancellation policy. Prowork reserves the right to charge you, or otherwise deduct applicable taxes in respect of such cancellation fee.</p>
                <p className='p-4'>7.5 &nbsp; Prowork does not designate any portion of your payment as a tip or gratuity to the Service Professional. Any representation by Pro Work to the effect that tipping is “voluntary”, “not required”, and/or “included” in the payments you make for Services is not intended to suggest that Pro Work provides any additional payments to Service Professionals. You understand and agree that while you are free to provide additional payment as a gratuity to any Service Professional who provides you with Services, you are under no obligation to do so. Gratuities are voluntary.</p>
            </div>
            <div className='pb-5 px-4 text-white'>
                <h2 class='font-bold text-[#f2da1d]'>8. Customer Conduct</h2>
                <p className='text-base p-4'>8.1 &nbsp; Prowork prohibits discrimination against Service Professionals, including on the basis of race, religion, caste, national origin, disability, sexual orientation, sex, marital status, gender identity, age, or any other characteristic that may be protected under applicable law. Such discrimination includes but is not limited to any refusal to accept Services based on any of these characteristics.</p>
                <p className='text-base p-4'>8.2 &nbsp; We request that you treat all Service Professionals with courtesy and respect, and that you provide them with a safe, clean, and appropriate location to perform the Services. Service Professionals shall be entitled to refuse to perform Services if you have not provided a safe, clean, and appropriate location for them, or you behave towards them in a manner which is discourteous, disrespectful, abusive, or otherwise inappropriate. We reserve the right to withhold access to the Services and otherwise limit your access to Services at our absolute discretion if you behave towards any Service Professional in a manner which is discourteous, disrespectful, or abusive, or which we otherwise deem to be inappropriate or unlawful.</p>
                <p className='text-base p-4'>8.3 &nbsp; You agree that you will be liable for discriminating against Service Professionals or for any failure, intentional or otherwise, to provide the Service Professionals a safe, clean, and appropriate location for them to perform the Pro Services. Additionally, you will also disclose any and all information that may have a bearing on the ability of the Service Professional to perform the Pro Services or impact the Services Professional’s health, safety, or well-being, to Prowork and the Service Professional.</p>
                <p className='text-base p-4'>8.4 &nbsp; You agree that in the event a Service Professional behaves in a manner that is discourteous, disrespectful, abusive, inappropriate, or in violation of the law, you shall be required to report such incident to <span className='text-green-500'>prowork24.7customercare@gmail.com</span>  at the earliest but in any event within 48 (forty eight) hours of such incident.</p>
            </div>
            <div className='pb-5 px-4 text-white'>
            <h2 class='font-bold text-[#f2da1d]'>9. Your Responsibilities</h2>
                    <p className='p-4'>9.1 &nbsp; You represent and warrant that all information that you provide in relation to the Services is complete, true, and correct on the date of agreeing to these Terms and shall continue to be complete, true, and correct while you avail the Services. Should any information that you provide change during the existence of these Terms, you undertake to immediately bring such change to our notice. We do not accept any responsibility or liability for any loss or damage that you may suffer or incur if any information, documentation, material, or data, provided to avail the Services is incorrect, incomplete, inaccurate, or misleading or if you fail to disclose any material fact.</p>
                    <p className='p-4'>9.2 &nbsp; You shall extend all cooperation to us in our defence of any proceedings that may be initiated against us due to a breach of your obligations or covenants under these Terms.</p>
                    <p className='p-4'>9.3 &nbsp;
                        In respect of the User Content, you represent and warrant that:
                        <span className='block px-10 py-2'>(a) &nbsp;&nbsp;&nbsp;&nbsp;you own all intellectual property rights (or have obtained all necessary permissions) to provide User Content and to grant the licences under these Terms;</span>
                        <span className='block px-10 py-2'>(b) &nbsp;&nbsp;&nbsp;&nbsp;you are solely responsible for all activities that occur on or through your account on the Platform and all User Content.</span>
                        <span className='block px-10 py-2'>(c) &nbsp;&nbsp;&nbsp;&nbsp;the User Content does not and shall not violate any of your obligations or responsibilities under other agreements;</span>
                        <span className='block px-10 py-2'>(d) &nbsp;&nbsp;&nbsp;&nbsp;the User Content does not and shall not violate, infringe, or misappropriate any intellectual property right or other proprietary right including the right of publicity or privacy of any person or entity.</span>
                        <span className='block px-10 py-2'>(e) &nbsp;&nbsp;&nbsp;&nbsp;the User Content does not and shall not contain any viruses, corrupted data, or other harmful, disruptive, or destructive files or content.</span>
                        <span className='block px-10 py-2'>(f) &nbsp;&nbsp;&nbsp;&nbsp;the User Content does not and shall not violate any third party rights;</span>
                        <span className='block px-10 py-2'>(g) &nbsp;&nbsp;&nbsp;&nbsp;the User Content (A) does not belong to any other person to which you do not have any right, (B) does not threaten the unity, integrity, defence, security or sovereignty of India, friendly relations with foreign states, public order, cause incitement to the commission of any cognisable offence, prevents investigation of any offence, or is insulting another nation, (C) is not defamatory, grossly harmful, blasphemous, paedophilic, invasive of another’s privacy, discriminatory based on gender, ethnically objectionable, disparaging, relating to, or encouraging money laundering or gambling, libellous, hateful, racist, violent, obscene, pornographic, unlawful, harmful to children, or (D) otherwise offensive, objectionable, or restricts, or inhibits, any other person from using or enjoying the Services.</span>
                    </p>
                    <p className='p-4'>9.4 &nbsp;
                        You shall not use the Services in any manner except as expressly permitted in these Terms. Without limiting the generality of the preceding sentence, you shall not:
                        <span className='block px-10 py-2'>(a) &nbsp;&nbsp;&nbsp;&nbsp;infringe any proprietary rights, including but not limited to copyrights, patents, trademarks, or trade secrets of any party;</span>
                        <span className='block px-10 py-2'>(b) &nbsp;&nbsp;&nbsp;&nbsp;except as may be provided hereunder, copy, display, distribute, modify, publish, reproduce, store, transmit, post, translate, create any derivative works from or license the Services;</span>
                        <span className='block px-10 py-2'>(c) &nbsp;&nbsp;&nbsp;&nbsp;use the Services to transmit any data, or send or upload any material that contains viruses, Trojan horses, worms, timebombs, keystroke loggers, spyware, adware, or any other harmful programmes, or similar computer code, designed to adversely affect the operation of any computer software or hardware;</span>
                        <span className='block px-10 py-2'>(d) &nbsp;&nbsp;&nbsp;&nbsp;use any robot, spider, other automated device, or manual process to monitor or copy the Services or any portion thereof;</span>
                        <span className='block px-10 py-2'>(e) &nbsp;&nbsp;&nbsp;&nbsp;engage in the systematic retrieval of content from the Services to create or compile, directly or indirectly, a collection, compilation, database, or directory;</span>
                        <span className='block px-10 py-2'>(f) &nbsp;&nbsp;&nbsp;&nbsp;use the Services in (A) any unlawful manner, (B) for fraudulent or malicious activities or (C) in any manner inconsistent with these Terms;</span>
                        <span className='block px-10 py-2'>(g) &nbsp;&nbsp;&nbsp;&nbsp;decompile, reverse engineer, or disassemble the Services;</span>
                        <span className='block px-10 py-2'>(h) &nbsp;&nbsp;&nbsp;&nbsp;link to, mirror, or frame, any portion of all or any of the Services; or</span>
                        <span className='block px-10 py-2'>(i) &nbsp;&nbsp;&nbsp;&nbsp;violate applicable laws in any manner.</span>
                    </p>

                <p className='p-4'>9.5 &nbsp;You warrant that you shall not engage in any activity that interferes with or disrupts the Services.</p>
                <p className='p-4'>9.6 &nbsp;You shall not attempt to gain unauthorised access to any portion or feature of the Services, any other systems or networks connected to the Services, to any of our servers, or through the Platform by hacking, password mining, or any other illegitimate means.</p>
                <p className='p-4'>9.7 &nbsp;You shall not directly or indirectly, in any capacity, solicit, attempt to influence, engage, approach, or accept or encourage the solicitations or approach of, a Service Professional from whom you have availed Services, to either terminate or otherwise cease their registration on or engagement with the Platform, or avail services the same as or similar to the Services independently, without booking the Services through your Account. You agree that this limitation is reasonable and fair and is necessary for the protection of the privacy and security of Service Professionals and that this will not preclude you from obtaining services the same as or similar to the Services through the Platform or other means. You further agree that any potential harm to Service Professionals from the non-enforcement of this clause far outweighs any potential harm to you.</p>
            </div>
            <div className='pb-5 px-4 text-white'>
                <h2 class='font-bold text-[#f2da1d]'>10. Feedback</h2>
                <p className='py-4'>We may request you to submit suggestions and other feedback, including bug reports, relating to the Services from time to time (“Feedback”). We may freely use, copy, disclose, publish, display, distribute, and exploit the Feedback we receive from you without any payment of royalty, acknowledgement, prior consent, or any other form of restriction arising out of your intellectual property rights.</p>
            </div>

            <div className='pb-5 px-4 text-white'>
            <h2 class='font-bold text-[#f2da1d]'>11. Terms and Terminations</h2>
                <p className='p-4'>11.1 &nbsp; These Terms shall remain in effect unless terminated in accordance with the terms hereunder.</p>
                <p className='p-4'>11.2 &nbsp; Upon termination of these Terms:
                    <span className='block px-10 py-2'>(i) &nbsp;&nbsp;&nbsp;&nbsp;the Account will expire;</span>
                    <span className='block px-10 py-2'>(ii) &nbsp;&nbsp;&nbsp;&nbsp;the Services will “time-out”; and</span>
                    <span className='block px-10 py-2'>(iii) &nbsp;&nbsp;&nbsp;&nbsp;these Terms shall terminate, except for those clauses that are expressly, or by implication, intended to survive termination or expiry.</span>
                </p>
            </div>

        </div>
    </div>
  )
}

export default Terms